.PHONY: run

run: Mastermind.class MastermindSolver.class Code.class
	java Mastermind

Mastermind.class: Mastermind.java
	javac Mastermind.java

MastermindSolver.class: MastermindSolver.java
	javac MastermindSolver.java

Code.class: Code.java
	javac Code.java

MathUtil.class: MathUtil.java
	javac MathUtil.java
