.PHONY: run

run: TestBarbie.class Barbie.class Toy.class
	java TestBarbie

Toy.class: Toy.java
	javac Toy.java

TestBarbie.class: TestBarbie.java
	javac TestBarbie.java

Barbie.class: Barbie.java
	javac Barbie.java
