name: CI for ICS4U Culminating Project Mastermind
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run unit tests
        run: |
          cd culminating-mastermind
          ./gradlew test
