name: CI for ICS4U Culminating Project Mastermind

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run unit tests
        run: |
          cd culminating-mastermind
          ./gradlew test

  javadoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build javadoc
        continue-on-error: true
        run: |
          cd culminating-mastermind
          ./gradlew javadoc

      - name: Upload javadoc
        uses: actions/upload-artifact@v4
        with:
          name: javadoc
          path: culminating-mastermind/app/build/docs/javadoc

  wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.1"
          bundler-cache: true
          cache-version: 0

      - name: Build wiki
        run: |
          cd culminating-mastermind/docs
          bundle install
          bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Upload wiki
        uses: actions/upload-artifact@v4
        with:
          name: wiki
          path: culminating-mastermind/docs/_site

  gh-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [javadoc, wiki]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Move javadoc to wiki
        run: |
          mkdir -p wiki/components
          mv javadoc/* wiki/components

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: wiki

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
